version: "3.9"

services:
  php:
    hostname: ${PHP_NAME}
    container_name: ${PHP_NAME}
    env_file:
      - .env
    user: ${UID}:${GID}
    build:
      context: ${PHP_CONTEXT}
      dockerfile: ${PHP_DOCKERFILE}
      args:
        PHP_VERSION: ${PHP_VERSION}
        PHP_CONFIG_SOURCE: ${PHP_CONFIG_SOURCE}
        PHP_CONFIG_TARGET: ${PHP_CONFIG_TARGET}
        PHP_CODE_SOURCE: ${PHP_CODE_SOURCE}
        PHP_CODE_TARGET: ${PHP_CODE_TARGET}
        PHP_ENTRYPOINT_SOURCE: ${PHP_ENTRYPOINT_SOURCE}
        PHP_ENTRYPOINT_TARGET: ${PHP_ENTRYPOINT_TARGET}
    ports:
      - ${PHP_PORT}:${PHP_PORT}
    volumes:
      - ${PHP_CODE_SOURCE}:${PHP_CODE_TARGET}
